name: Tests
on: [push, pull_request]
jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        gemfile: [gemfiles/Gemfile.paperclip-6.0.x, Gemfile]
        ruby: [2.6, 2.7]
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake
